### ISSUE TITLE
Biomes with more than one word

### ISSUE THREAD

**Issue by Kaspian24** [Traben-0/EmissiveMod#12]
Biomes with multiple words like soul sand valley don't work.  I tried soul_sand_valley, SoulSandValley and "soul sand valley" formats and none seem to work. Only biomes with one word work like plains or swamp.

**Comment by Kaspian24** [comment]
badlands doesn't seem to work either

**Comment by Kaspian24** [comment]
mushroom_fields don't work but just mushroom work

**Comment by Traben-0** [comment]
Turns out I was grabbing the biome category not the actual name, this has been fixed for version V2.1.4, which should be releasing tonight, soul_sand_valley, Soul_Sand_Valley, & minecraft:soul_sand_valley are all correct and now working examples, "soul sand valley" will not be working for the time being
